# Site settings
title:       Qiong Wu
email:       qiongwu@utexas.edu
author:      Qiong Wu
source: source
destination: build
description: "The personal website of Qiong Wu. He is a programmer, hacker, algorist, and tennis player."
baseurl:     ""
url:         "http://wqiong.com"
date_format: "%b %-d, %Y"
safe: false

# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10

# Social icons
github_username: creasyw
bitbucket_username:
stackoverflow_id:
twitter_username: creasywuqiong
google_plus_id:
linkedin_username: creasywuqiong
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
plugins:
  - jekyll-paginate

markdown:     kramdown

redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  sass_dir: _sass
  style: compressed
  compressed: true


#############
# Resume settings
resume_avatar:                  "false"
resume_name:                    "Qiong Wu"
resume_title:                   ""
#resume_contact_email:           ""

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "http://www.github.com/creasyw"
  resume_twitter_url:           "http://www.twitter.com/creasywuqiong"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "http://www.facebook.com/creasy.wu.98"
  resume_linkedin_url:          "https://www.linkedin.com/in/qiongw"
  resume_instagram_url:         "http://instagram.com/kelisier"
  #resume_website_url:           "http://wqiong.com"

# Design settings
resume_theme:                   default
